services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE=devsecretdevsecretdevsecretdevsecretdevsecretdevsecret12
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@db:5432/app_dev
      - OPENAI_API_KEY=${OPENAI_API_KEY:-changeme}
    volumes:
      - .:/app:cached
      - deps:/app/deps
      - build:/app/_build
      - widget_node_modules:/app/assets/widget/node_modules
    command: ["./bin/dev"]
    # Speeds up file change notifications on macOS/Windows
    # use polling for Vite if needed: VITE_FORCE_POLLING=1
    tty: true
    stdin_open: true

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  deps:
  build:
  widget_node_modules:
  pgdata:
